// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcM-QnaybylgFiaSQuCMItalQK_tbSyNA',
    appId: '1:602374798151:web:746e05346b1d09a1242a62',
    messagingSenderId: '602374798151',
    projectId: 'teddy-bear-s-diary',
    authDomain: 'teddy-bear-s-diary.firebaseapp.com',
    storageBucket: 'teddy-bear-s-diary.firebasestorage.app',
    measurementId: 'G-3V5C292E39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtippfZ7Geq0YE-KAkVYfHm1bbDD8gtdw',
    appId: '1:602374798151:android:1c18b8a86a06cb3e242a62',
    messagingSenderId: '602374798151',
    projectId: 'teddy-bear-s-diary',
    storageBucket: 'teddy-bear-s-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC3aT85TvZnYs7sQX2PGGWu0Zo2VUjqHs',
    appId: '1:602374798151:ios:422cf6385d1379b4242a62',
    messagingSenderId: '602374798151',
    projectId: 'teddy-bear-s-diary',
    storageBucket: 'teddy-bear-s-diary.firebasestorage.app',
    iosBundleId: 'com.example.create',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC3aT85TvZnYs7sQX2PGGWu0Zo2VUjqHs',
    appId: '1:602374798151:ios:422cf6385d1379b4242a62',
    messagingSenderId: '602374798151',
    projectId: 'teddy-bear-s-diary',
    storageBucket: 'teddy-bear-s-diary.firebasestorage.app',
    iosBundleId: 'com.example.create',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcM-QnaybylgFiaSQuCMItalQK_tbSyNA',
    appId: '1:602374798151:web:10d7fd46511e6792242a62',
    messagingSenderId: '602374798151',
    projectId: 'teddy-bear-s-diary',
    authDomain: 'teddy-bear-s-diary.firebaseapp.com',
    storageBucket: 'teddy-bear-s-diary.firebasestorage.app',
    measurementId: 'G-PJLG5NM8H5',
  );
}
