// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:teddyBear/data/model/message.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MessageAdapter());
    registerAdapter(MessageTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MessageAdapter());
    registerAdapter(MessageTypeAdapter());
  }
}
